package memory

import (
	"fmt"
	"strings"
)

func (s *Store) GenerateAgentsMD() (string, error) {
	var b strings.Builder
	b.WriteString("# AGENTS.md\n<!-- Auto-generated by devmem. Do not edit manually. -->\n<!-- Regenerate with: devmem_generate_rules -->\n\n")

	feature, featureErr := s.GetActiveFeature()

	writeItems := func(title, empty string, load func() ([]string, error)) {
		b.WriteString("## " + title + "\n\n")
		if featureErr != nil {
			b.WriteString(empty + "\n\n")
			return
		}
		items, err := load()
		if err != nil || len(items) == 0 {
			b.WriteString(empty + "\n\n")
			return
		}
		for _, item := range items {
			b.WriteString("- " + strings.ReplaceAll(item, "\n", " ") + "\n")
		}
		b.WriteString("\n")
	}

	writeItems("Project Context", "No active feature. Start a feature to populate context.", func() ([]string, error) {
		facts, err := s.GetActiveFacts(feature.ID)
		if err != nil {
			return nil, err
		}
		out := make([]string, len(facts))
		for i, f := range facts {
			out[i] = fmt.Sprintf("%s %s %s", f.Subject, f.Predicate, f.Object)
		}
		return out, nil
	})

	b.WriteString("## Active Feature\n\n")
	if featureErr == nil {
		b.WriteString(fmt.Sprintf("**%s**", feature.Name))
		if feature.Description != "" {
			b.WriteString(fmt.Sprintf(" — %s", feature.Description))
		}
		b.WriteString("\n")
		if feature.Branch != "" {
			b.WriteString(fmt.Sprintf("- Branch: %s\n", feature.Branch))
		}
		b.WriteString(fmt.Sprintf("- Status: %s\n", feature.Status))
		if pi := s.loadPlanInfo(s.db.Reader(), feature.ID); pi != nil {
			b.WriteString(fmt.Sprintf("- Plan: %s (%d/%d steps completed)\n", pi.Title, pi.CompletedStep, pi.TotalSteps))
		}
	} else {
		b.WriteString("No active feature.\n")
	}
	b.WriteString("\n")

	noteItems := func(noteType string) func() ([]string, error) {
		return func() ([]string, error) {
			notes, err := s.ListNotes(feature.ID, noteType, 10)
			if err != nil {
				return nil, err
			}
			out := make([]string, len(notes))
			for i, n := range notes {
				out[i] = n.Content
			}
			return out, nil
		}
	}
	writeItems("Key Decisions", "No decisions recorded yet.", noteItems("decision"))
	writeItems("Current Blockers", "No blockers.", noteItems("blocker"))
	writeItems("Next Steps", "No next steps recorded yet.", noteItems("next_step"))

	b.WriteString("## Session Protocol\n\nAt the start of every session, call devmem_briefing to load context.\nWhen making decisions, call devmem_remember with type=\"decision\".\nBefore ending a session, call devmem_end_session with a summary.\n")

	return b.String(), nil
}
