package memory

import (
	"fmt"
	"strings"
)

// GenerateAgentsMD reads from memory and generates an AGENTS.md file content.
// It includes project context from facts, active feature info, key decisions,
// current blockers, and next steps.
func (s *Store) GenerateAgentsMD() (string, error) {
	var b strings.Builder

	b.WriteString("# AGENTS.md\n")
	b.WriteString("<!-- Auto-generated by devmem. Do not edit manually. -->\n")
	b.WriteString("<!-- Regenerate with: devmem_generate_rules -->\n\n")

	// Get the active feature (if any)
	feature, featureErr := s.GetActiveFeature()

	// --- Project Context (from active facts) ---
	b.WriteString("## Project Context\n\n")
	if featureErr == nil {
		facts, err := s.GetActiveFacts(feature.ID)
		if err == nil && len(facts) > 0 {
			for _, f := range facts {
				b.WriteString(fmt.Sprintf("- %s %s %s\n", f.Subject, f.Predicate, f.Object))
			}
		} else {
			b.WriteString("No project facts recorded yet.\n")
		}
	} else {
		b.WriteString("No active feature. Start a feature to populate context.\n")
	}
	b.WriteString("\n")

	// --- Active Feature ---
	b.WriteString("## Active Feature\n\n")
	if featureErr == nil {
		b.WriteString(fmt.Sprintf("**%s**", feature.Name))
		if feature.Description != "" {
			b.WriteString(fmt.Sprintf(" — %s", feature.Description))
		}
		b.WriteString("\n")
		if feature.Branch != "" {
			b.WriteString(fmt.Sprintf("- Branch: %s\n", feature.Branch))
		}
		b.WriteString(fmt.Sprintf("- Status: %s\n", feature.Status))

		// Plan progress
		pi := s.loadPlanInfo(s.db.Reader(), feature.ID)
		if pi != nil {
			b.WriteString(fmt.Sprintf("- Plan: %s (%d/%d steps completed)\n", pi.Title, pi.CompletedStep, pi.TotalSteps))
		}
	} else {
		b.WriteString("No active feature.\n")
	}
	b.WriteString("\n")

	// --- Key Decisions ---
	b.WriteString("## Key Decisions\n\n")
	if featureErr == nil {
		decisions, err := s.ListNotes(feature.ID, "decision", 10)
		if err == nil && len(decisions) > 0 {
			for _, d := range decisions {
				b.WriteString(fmt.Sprintf("- %s\n", strings.ReplaceAll(d.Content, "\n", " ")))
			}
		} else {
			b.WriteString("No decisions recorded yet.\n")
		}
	} else {
		b.WriteString("No decisions recorded yet.\n")
	}
	b.WriteString("\n")

	// --- Current Blockers ---
	b.WriteString("## Current Blockers\n\n")
	if featureErr == nil {
		blockers, err := s.ListNotes(feature.ID, "blocker", 10)
		if err == nil && len(blockers) > 0 {
			for _, bl := range blockers {
				b.WriteString(fmt.Sprintf("- %s\n", strings.ReplaceAll(bl.Content, "\n", " ")))
			}
		} else {
			b.WriteString("No blockers.\n")
		}
	} else {
		b.WriteString("No blockers.\n")
	}
	b.WriteString("\n")

	// --- Next Steps ---
	b.WriteString("## Next Steps\n\n")
	if featureErr == nil {
		nextSteps, err := s.ListNotes(feature.ID, "next_step", 10)
		if err == nil && len(nextSteps) > 0 {
			for _, ns := range nextSteps {
				b.WriteString(fmt.Sprintf("- %s\n", strings.ReplaceAll(ns.Content, "\n", " ")))
			}
		} else {
			b.WriteString("No next steps recorded yet.\n")
		}
	} else {
		b.WriteString("No next steps recorded yet.\n")
	}
	b.WriteString("\n")

	// --- Session Protocol ---
	b.WriteString("## Session Protocol\n\n")
	b.WriteString("At the start of every session, call devmem_briefing to load context.\n")
	b.WriteString("When making decisions, call devmem_remember with type=\"decision\".\n")
	b.WriteString("Before ending a session, call devmem_end_session with a summary.\n")

	return b.String(), nil
}
