package memory_test

import (
	"strings"
	"testing"
)

func TestGenerateAgentsMD_WithFacts(t *testing.T) {
	store := newTestStore(t)

	f, err := store.CreateFeature("test-feature", "A test feature")
	if err != nil {
		t.Fatalf("CreateFeature: %v", err)
	}

	_, err = store.CreateFact(f.ID, "", "backend", "uses", "Go")
	if err != nil {
		t.Fatalf("CreateFact: %v", err)
	}
	_, err = store.CreateFact(f.ID, "", "database", "is", "SQLite")
	if err != nil {
		t.Fatalf("CreateFact: %v", err)
	}

	md, err := store.GenerateAgentsMD()
	if err != nil {
		t.Fatalf("GenerateAgentsMD: %v", err)
	}

	if !strings.Contains(md, "## Project Context") {
		t.Error("expected Project Context section")
	}
	if !strings.Contains(md, "backend uses Go") {
		t.Errorf("expected fact 'backend uses Go' in output, got:\n%s", md)
	}
	if !strings.Contains(md, "database is SQLite") {
		t.Errorf("expected fact 'database is SQLite' in output, got:\n%s", md)
	}
}

func TestGenerateAgentsMD_WithDecisions(t *testing.T) {
	store := newTestStore(t)

	f, err := store.CreateFeature("decision-feature", "Feature with decisions")
	if err != nil {
		t.Fatalf("CreateFeature: %v", err)
	}

	_, err = store.CreateNote(f.ID, "", "Use dependency injection for testability", "decision")
	if err != nil {
		t.Fatalf("CreateNote decision 1: %v", err)
	}
	_, err = store.CreateNote(f.ID, "", "Prefer composition over inheritance", "decision")
	if err != nil {
		t.Fatalf("CreateNote decision 2: %v", err)
	}

	md, err := store.GenerateAgentsMD()
	if err != nil {
		t.Fatalf("GenerateAgentsMD: %v", err)
	}

	if !strings.Contains(md, "## Key Decisions") {
		t.Error("expected Key Decisions section")
	}
	if !strings.Contains(md, "Use dependency injection for testability") {
		t.Errorf("expected decision content in output, got:\n%s", md)
	}
	if !strings.Contains(md, "Prefer composition over inheritance") {
		t.Errorf("expected second decision content in output, got:\n%s", md)
	}
}

func TestGenerateAgentsMD_WithBlockers(t *testing.T) {
	store := newTestStore(t)

	f, err := store.CreateFeature("blocker-feature", "Feature with blockers")
	if err != nil {
		t.Fatalf("CreateFeature: %v", err)
	}

	_, err = store.CreateNote(f.ID, "", "Waiting on API key from provider", "blocker")
	if err != nil {
		t.Fatalf("CreateNote blocker: %v", err)
	}

	md, err := store.GenerateAgentsMD()
	if err != nil {
		t.Fatalf("GenerateAgentsMD: %v", err)
	}

	if !strings.Contains(md, "## Current Blockers") {
		t.Error("expected Current Blockers section")
	}
	if !strings.Contains(md, "Waiting on API key from provider") {
		t.Errorf("expected blocker content in output, got:\n%s", md)
	}
}

func TestGenerateAgentsMD_NoData(t *testing.T) {
	store := newTestStore(t)

	md, err := store.GenerateAgentsMD()
	if err != nil {
		t.Fatalf("GenerateAgentsMD: %v", err)
	}

	// Should still produce valid markdown with all sections
	if !strings.Contains(md, "# AGENTS.md") {
		t.Error("expected AGENTS.md header")
	}
	if !strings.Contains(md, "## Project Context") {
		t.Error("expected Project Context section")
	}
	if !strings.Contains(md, "## Active Feature") {
		t.Error("expected Active Feature section")
	}
	if !strings.Contains(md, "## Key Decisions") {
		t.Error("expected Key Decisions section")
	}
	if !strings.Contains(md, "## Current Blockers") {
		t.Error("expected Current Blockers section")
	}
	if !strings.Contains(md, "## Next Steps") {
		t.Error("expected Next Steps section")
	}
	if !strings.Contains(md, "## Session Protocol") {
		t.Error("expected Session Protocol section")
	}
	if !strings.Contains(md, "No active feature") {
		t.Error("expected 'No active feature' placeholder when no feature exists")
	}
}

func TestGenerateAgentsMD_IncludesSessionProtocol(t *testing.T) {
	store := newTestStore(t)

	// Even with no data, the session protocol section should be present
	md, err := store.GenerateAgentsMD()
	if err != nil {
		t.Fatalf("GenerateAgentsMD: %v", err)
	}

	if !strings.Contains(md, "## Session Protocol") {
		t.Error("expected Session Protocol section")
	}
	if !strings.Contains(md, "devmem_briefing") {
		t.Error("expected session protocol to mention devmem_briefing")
	}
	if !strings.Contains(md, "devmem_remember") {
		t.Error("expected session protocol to mention devmem_remember")
	}
	if !strings.Contains(md, "devmem_end_session") {
		t.Error("expected session protocol to mention devmem_end_session")
	}
	if !strings.Contains(md, "Auto-generated by devmem") {
		t.Error("expected auto-generated comment")
	}
	if !strings.Contains(md, "devmem_generate_rules") {
		t.Error("expected regeneration hint mentioning devmem_generate_rules")
	}
}

func TestGenerateAgentsMD_WithNextSteps(t *testing.T) {
	store := newTestStore(t)

	f, err := store.CreateFeature("nextstep-feature", "Feature with next steps")
	if err != nil {
		t.Fatalf("CreateFeature: %v", err)
	}

	_, err = store.CreateNote(f.ID, "", "Implement the search API endpoint", "next_step")
	if err != nil {
		t.Fatalf("CreateNote next_step: %v", err)
	}
	_, err = store.CreateNote(f.ID, "", "Add integration tests for auth flow", "next_step")
	if err != nil {
		t.Fatalf("CreateNote next_step 2: %v", err)
	}

	md, err := store.GenerateAgentsMD()
	if err != nil {
		t.Fatalf("GenerateAgentsMD: %v", err)
	}

	if !strings.Contains(md, "## Next Steps") {
		t.Error("expected Next Steps section")
	}
	if !strings.Contains(md, "Implement the search API endpoint") {
		t.Errorf("expected next step content in output, got:\n%s", md)
	}
	if !strings.Contains(md, "Add integration tests for auth flow") {
		t.Errorf("expected second next step content in output, got:\n%s", md)
	}
}

func TestGenerateAgentsMD_MultilineNotesFlattenedToSingleLine(t *testing.T) {
	store := newTestStore(t)

	f, err := store.CreateFeature("multiline-feature", "Feature with multiline notes")
	if err != nil {
		t.Fatalf("CreateFeature: %v", err)
	}

	_, err = store.CreateNote(f.ID, "", "Decision line 1\nDecision line 2", "decision")
	if err != nil {
		t.Fatalf("CreateNote: %v", err)
	}

	md, err := store.GenerateAgentsMD()
	if err != nil {
		t.Fatalf("GenerateAgentsMD: %v", err)
	}

	// The decision should appear on a single line in the markdown list
	if !strings.Contains(md, "- Decision line 1 Decision line 2") {
		t.Errorf("expected multiline note to be flattened, got:\n%s", md)
	}
}
